In [7]:
import pandas as pd
data_csv = pd.read_csv("raw_data.csv")

In [8]:
data_csv

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [12]:
data_json = pd.read_json("emp_data.json")
print(data_json)
data_json.info()
data_json.describe()

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000